services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - API_KEY=${API_KEY}
      - S3_BUCKET_URL=${S3_BUCKET_URL}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
    env_file:
      - ./.env

secrets:
  aws:
    file: $HOME/.aws/credentials