stages:
  prepare:
    cmd:  python src/stroke_prediction/preprocess.py data/raw/healthcare-dataset-stroke-data.csv data/processed/ -y
    deps:
    - data/raw/healthcare-dataset-stroke-data.csv
    - src/stroke_prediction/preprocess.py
    outs:
    - data/processed/train-stroke-data.feather
    - data/processed/test-stroke-data.feather
