stages:
  prepare:
    cmd:  python src/stroke_prediction/preprocess.py preprocess-data data/raw/healthcare-dataset-stroke-data.csv data/processed/ -y
    params:
      - preprocess.test_size
      - preprocess.val_size
      - random_seed
    deps:
    - data/raw/healthcare-dataset-stroke-data.csv
    - src/stroke_prediction/preprocess.py
    outs:
    - data/processed/train-stroke-data.parquet
    - data/processed/val-stroke-data.parquet
    - data/processed/test-stroke-data.parquet
  
  resample:
    cmd:  python src/stroke_prediction/preprocess.py resample-data data/processed/train-stroke-data.parquet data/processed/train-stroke-data-resampled.parquet -y
    params:
      - random_seed
    deps:
    - data/processed/train-stroke-data.parquet
    - src/stroke_prediction/preprocess.py
    outs:
    - data/processed/train-stroke-data-resampled.parquet
  
  train:
    cmd:  python src/stroke_prediction/train.py data/processed/train-stroke-data-resampled.parquet data/processed/val-stroke-data.parquet models/catboost-model.cbm -y
    params:
      - model.colsample_bylevel
      - model.depth
      - model.l2_leaf_reg
      - model.boosting_type
      - model.bootstrap_type
      - random_seed
    deps:
    - data/processed/train-stroke-data-resampled.parquet
    - data/processed/val-stroke-data.parquet
    - src/stroke_prediction/train.py
    outs:
    - models/catboost-model.cbm
